compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  '@apidevtools/json-schema-ref-parser@10.1.0':
    dependencies:
      node-fetch: 'npm:node-fetch@^2.6.2'

yarnPath: .yarn/releases/yarn-4.0.1.cjs
