[build.environment]
  NODE_VERSION = "16.15.0"

[[headers]]
  for = "/*.schema.json"
  [headers.values]
    Content-Type = "application/schema+json"

[[redirects]]
  from = "/*.schema"
  to = "/:splat.schema.json"
  status = 301