[build.environment]
  NODE_VERSION = "20.9.0"
  YARN_VERSION = "4.1.1"
  RUBY_VERSION = "3.0.2"

[[headers]]
  for = "/*.schema.json"
  [headers.values]
    Content-Type = "application/schema+json"

[[redirects]]
  from = "/*.schema"
  to = "/:splat.schema.json"
  status = 301