# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish alpha

on:
  push:
    branches:
      - dev

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npx lerna bootstrap
      - run: npx lerna publish --canary --yes --preid alpha --dist-tag alpha
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npx lerna bootstrap
      - run: npx lerna publish --canary --yes --preid alpha --dist-tag alpha
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
