name: Run Spectral

on: [push, pull_request]

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # "Build" the schemas
      - uses: actions/setup-node@v1
      - run: yarn

      # Run Spectral
      - uses: stoplightio/spectral-action@v0.6.1
        with:
          spectral_ruleset: .spectral.json
          file_glob: 'packages/formats/lib/**/*.schema.json'
